/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mood;

import food.*;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JTextField;

/**
 *
 * @author Kyle
 */
public class EditMoodPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodCreatePanel
     */
    public EditMoodPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aMField = new javax.swing.JTextField();
        aMLabel = new javax.swing.JLabel();
        aMoodCnlBtn = new javax.swing.JButton();
        aMSliderMinLabel = new javax.swing.JLabel();
        aMSliderMaxLabel = new javax.swing.JLabel();
        aMoodUpdBtn = new javax.swing.JButton();
        aMSlider = new javax.swing.JSlider();

        aMField.setText("Ex. Satisfied");

        aMLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aMLabel.setText("Add Mood");
        aMLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        aMoodCnlBtn.setText("Cancel");
        aMoodCnlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMoodCnlBtnActionPerformed(evt);
            }
        });

        aMSliderMinLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aMSliderMinLabel.setText("0");

        aMSliderMaxLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aMSliderMaxLabel.setText("10");

        aMoodUpdBtn.setText("Submit");
        aMoodUpdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMoodUpdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aMoodCnlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(aMoodUpdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aMSliderMinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aMLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aMField)
                                    .addComponent(aMSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aMSliderMaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(aMLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aMField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aMSliderMinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(aMSliderMaxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(aMSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aMoodCnlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aMoodUpdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aMoodCnlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMoodCnlBtnActionPerformed
        //Return
    }//GEN-LAST:event_aMoodCnlBtnActionPerformed

    private void aMoodUpdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMoodUpdBtnActionPerformed
        //Update
    }//GEN-LAST:event_aMoodUpdBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aMField;
    private javax.swing.JLabel aMLabel;
    private javax.swing.JSlider aMSlider;
    private javax.swing.JLabel aMSliderMaxLabel;
    private javax.swing.JLabel aMSliderMinLabel;
    private javax.swing.JButton aMoodCnlBtn;
    private javax.swing.JButton aMoodUpdBtn;
    // End of variables declaration//GEN-END:variables
    
    
    
    public javax.swing.JTextField getMField(){
        return this.aMField;
    }
    
    public void setMField(javax.swing.JTextField eMField){
        this.aMField = eMField;
    }
    
    public javax.swing.JSlider getMSlider(){
        return this.aMSlider;
    }
    
    public void setMSlider(javax.swing.JSlider eMSlider){
        this.aMSlider = eMSlider;
    }
    
}
