/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mood;

import food.*;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JTextField;
import models.Mood;

/**
 *
 * @author Kyle
 */
public class EditMoodPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodCreatePanel
     */
    public EditMoodPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eMField = new javax.swing.JTextField();
        eMLabel = new javax.swing.JLabel();
        eMoodCnlBtn = new javax.swing.JButton();
        eMSliderMinLabel = new javax.swing.JLabel();
        eMSliderMaxLabel = new javax.swing.JLabel();
        eMoodUpdBtn = new javax.swing.JButton();
        eMSlider = new javax.swing.JSlider();

        eMField.setText("Ex. Satisfied");

        eMLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eMLabel.setText("Edit Mood");
        eMLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        eMoodCnlBtn.setText("Cancel");
        eMoodCnlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMoodCnlBtnActionPerformed(evt);
            }
        });

        eMSliderMinLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eMSliderMinLabel.setText("0");

        eMSliderMaxLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eMSliderMaxLabel.setText("10");

        eMoodUpdBtn.setText("Update");
        eMoodUpdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMoodUpdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eMoodCnlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(eMoodUpdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eMSliderMinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eMLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eMField)
                                    .addComponent(eMSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eMSliderMaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(eMLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eMField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eMSliderMinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(eMSliderMaxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(eMSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMoodCnlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eMoodUpdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eMoodCnlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMoodCnlBtnActionPerformed
        //Return
    }//GEN-LAST:event_eMoodCnlBtnActionPerformed

    private void eMoodUpdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMoodUpdBtnActionPerformed
        //Create
        Mood newMood = new Mood();
        newMood.setName(eMField.toString());
        newMood.setAmount(eMSlider.getValue());
    }//GEN-LAST:event_eMoodUpdBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eMField;
    private javax.swing.JLabel eMLabel;
    private javax.swing.JSlider eMSlider;
    private javax.swing.JLabel eMSliderMaxLabel;
    private javax.swing.JLabel eMSliderMinLabel;
    private javax.swing.JButton eMoodCnlBtn;
    private javax.swing.JButton eMoodUpdBtn;
    // End of variables declaration//GEN-END:variables
    
    
    
    public javax.swing.JTextField getMField(){
        return this.eMField;
    }
    
    public void setMField(javax.swing.JTextField eMField){
        this.eMField = eMField;
    }
    
    public javax.swing.JSlider getMSlider(){
        return this.eMSlider;
    }
    
    public void setMSlider(javax.swing.JSlider eMSlider){
        this.eMSlider = eMSlider;
    }

    public JButton geteMoodCnlBtn() {
        return eMoodCnlBtn;
    }

    public void seteMoodCnlBtn(JButton eMoodCnlBtn) {
        this.eMoodCnlBtn = eMoodCnlBtn;
    }

    public JButton geteMoodUpdBtn() {
        return eMoodUpdBtn;
    }

    public void seteMoodUpdBtn(JButton eMoodUpdBtn) {
        this.eMoodUpdBtn = eMoodUpdBtn;
    }
    
}
