/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mood;

import food.*;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JTextField;
import models.Mood;

/**
 *
 * @author Kyle
 */
public class EditMoodPanel extends javax.swing.JPanel {

    private int accountID;
    /**
     * Creates new form FoodCreatePanel
     */
    public EditMoodPanel(int accountID) {
        initComponents();
        this.accountID = accountID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateButton = new javax.swing.JButton();
        updateNameLabel = new javax.swing.JLabel();
        updateNameTextField = new javax.swing.JTextField();
        updatePortionLabel = new javax.swing.JLabel();
        updateComboBox = new javax.swing.JComboBox<>();

        updateButton.setText("Update");

        updateNameLabel.setText("Mood:");

        updatePortionLabel.setText("Rating: ");

        updateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addGap(170, 170, 170))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updatePortionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateComboBox, 0, 106, Short.MAX_VALUE)
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateNameTextField)
                        .addGap(143, 143, 143))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateNameLabel)
                    .addComponent(updateNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePortionLabel)
                    .addComponent(updateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton updateButton;
    private javax.swing.JComboBox<String> updateComboBox;
    private javax.swing.JLabel updateNameLabel;
    private javax.swing.JTextField updateNameTextField;
    private javax.swing.JLabel updatePortionLabel;
    // End of variables declaration//GEN-END:variables
    
    
    


    public JButton getUpdateButton() {
        return updateButton;
    }

    public void setUpdateBUtton(JButton updateButton) {
        this.updateButton = updateButton;
    }
    
        /**
     * @return the updateComboBox
     */
    public javax.swing.JComboBox<String> getUpdateComboBox() {
        return updateComboBox;
    }

    /**
     * @return the updateNameTextField
     */
    public javax.swing.JTextField getUpdateNameTextField() {
        return updateNameTextField;
    }

    /**
     * @param updateNameTextField the updateNameTextField to set
     */
    public void setUpdateNameTextField(javax.swing.JTextField updateNameTextField) {
        this.updateNameTextField = updateNameTextField;
    }
    
}
