/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drink;

/**
 *
 * @author Dylan
 */
public class AddDrinkPanel extends javax.swing.JPanel {
    
    private int accountID;

    /**
     * Creates new form AddDrinkPanel
     */
    public AddDrinkPanel(int accountID) {
        initComponents();
        this.accountID = accountID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drinkLabel = new javax.swing.JLabel();
        drinkField = new javax.swing.JTextField();
        portionLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        comboBox = new javax.swing.JComboBox<>();

        drinkLabel.setText("Drink");

        drinkField.setText("Ex. Water");
        drinkField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkFieldActionPerformed(evt);
            }
        });

        portionLabel.setText("Portion");

        submitButton.setText("Submit");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large"}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(portionLabel)
                            .addComponent(drinkLabel)
                            .addComponent(drinkField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(submitButton)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(drinkLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drinkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(portionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(submitButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void drinkFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinkFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JTextField drinkField;
    private javax.swing.JLabel drinkLabel;
    private javax.swing.JLabel portionLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
    
    public javax.swing.JTextField getDrinkField(){
        return this.drinkField;
    }
    
    public void setDrinkField(javax.swing.JTextField drinkField){
        this.drinkField = drinkField;
    }
    
    public javax.swing.JLabel getDrinkLabel(){
        return this.drinkLabel;
    }
    
    public javax.swing.JComboBox getComboBox(){
        return this.comboBox;
    }

    
    public javax.swing.JButton getSubmitButton(){
        return this.submitButton;
    }
    
    public void setSubmitButton(javax.swing.JButton submitButton){
        this.submitButton = submitButton;
    }
}
