/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drink;

/**
 *
 * @author Dylan
 */
public class AddDrinkPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDrinkPanel
     */
    public AddDrinkPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodLabel = new javax.swing.JLabel();
        foodField = new javax.swing.JTextField();
        portionLabel = new javax.swing.JLabel();
        smallRadio = new javax.swing.JRadioButton();
        mediumRadio = new javax.swing.JRadioButton();
        largeRadio = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();

        foodLabel.setText("Drink");

        foodField.setText("Ex. Water");
        foodField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodFieldActionPerformed(evt);
            }
        });

        portionLabel.setText("Portion");

        smallRadio.setText("Small");

        mediumRadio.setText("Medium");

        largeRadio.setText("Large");

        submitButton.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(largeRadio)
                            .addComponent(mediumRadio)
                            .addComponent(smallRadio)
                            .addComponent(portionLabel)
                            .addComponent(foodLabel)
                            .addComponent(foodField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(submitButton)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(foodLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(portionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(smallRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mediumRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(largeRadio)
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void foodFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField foodField;
    private javax.swing.JLabel foodLabel;
    private javax.swing.JRadioButton largeRadio;
    private javax.swing.JRadioButton mediumRadio;
    private javax.swing.JLabel portionLabel;
    private javax.swing.JRadioButton smallRadio;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
public javax.swing.JTextField getFoodField(){
        return this.foodField;
    }
    
    public void setFoodField(javax.swing.JTextField foodField){
        this.foodField = foodField;
    }
    
    public javax.swing.JLabel getFoodLabel(){
        return this.foodLabel;
    }
    
    public javax.swing.JRadioButton getLargeRadio(){
        return this.largeRadio;
    }
    
    public void setLargeRadio(javax.swing.JRadioButton largeRadio){
        this.largeRadio = largeRadio;
    }
    
    public javax.swing.JRadioButton getSmallRadio(){
        return this.smallRadio;
    }
    
    public void setSmallRadio(javax.swing.JRadioButton smallRadio){
        this.smallRadio = smallRadio;
    }
    
    public javax.swing.JRadioButton getMediumRadio(){
        return this.mediumRadio;
    }
    
    public void setMediumRadio(javax.swing.JRadioButton mediumRadio){
        this.mediumRadio = mediumRadio;
    }
    
    public javax.swing.JButton getSubmitButton(){
        return this.submitButton;
    }
    
    public void setSubmitButton(javax.swing.JButton submitButton){
        this.submitButton = submitButton;
    }
}
