/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drink;

/**
 *
 * @author Kyle
 */
public class EditDrinkPanel extends javax.swing.JPanel {

    private int accountID;

    /**
     * Creates new form EditDrinkPanel
     */
    public EditDrinkPanel(int accountID) {
        initComponents();
        this.accountID = accountID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateButton = new javax.swing.JButton();
        updateNameLabel = new javax.swing.JLabel();
        updatePortionLabel = new javax.swing.JLabel();
        updateNameTextField = new javax.swing.JTextField();
        updateComboBox = new javax.swing.JComboBox<>();

        updateButton.setText("Update");

        updateNameLabel.setText("Name:");

        updatePortionLabel.setText("Portion:");

        updateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large"}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(updateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updatePortionLabel)
                                .addGap(18, 18, 18)
                                .addComponent(updateComboBox, 0, 106, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(updateNameTextField)))))
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateNameLabel)
                    .addComponent(updateNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePortionLabel)
                    .addComponent(updateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton updateButton;
    private javax.swing.JComboBox<String> updateComboBox;
    private javax.swing.JLabel updateNameLabel;
    private javax.swing.JTextField updateNameTextField;
    private javax.swing.JLabel updatePortionLabel;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getUpdateButton() {
        return this.updateButton;
    }

    /**
     * @return the accountID
     */
    public int getAccountID() {
        return accountID;
    }

    /**
     * @param accountID the accountID to set
     */
    public void setAccountID(int accountID) {
        this.accountID = accountID;
    }

    /**
     * @return the updateComboBox
     */
    public javax.swing.JComboBox<String> getUpdateComboBox() {
        return updateComboBox;
    }

    /**
     * @return the updateNameTextField
     */
    public javax.swing.JTextField getUpdateNameTextField() {
        return updateNameTextField;
    }

    /**
     * @param updateNameTextField the updateNameTextField to set
     */
    public void setUpdateNameTextField(javax.swing.JTextField updateNameTextField) {
        this.updateNameTextField = updateNameTextField;
    }
}
