/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DesignSelection;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSlider;
import javax.swing.JSpinner;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author BasicPanda
 */
public class FoodMoodEntryForm extends javax.swing.JPanel {

    /**
     * Creates new form FoodMoodEntryForm
     */
    public FoodMoodEntryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JTabbedPane();
        foodPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        foodInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        foodLrgBtn = new javax.swing.JRadioButton();
        foodMedBtn = new javax.swing.JRadioButton();
        foodSmlBtn = new javax.swing.JRadioButton();
        toDrinkBtn = new javax.swing.JButton();
        foodScroll = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        drinkPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        drinkInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        drinkLrgBtn = new javax.swing.JRadioButton();
        drinkMedBtn = new javax.swing.JRadioButton();
        drinkSmlBtn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        drinkScroll = new javax.swing.JSpinner();
        toMoodBtn = new javax.swing.JButton();
        moodPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        moodInput = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        eMSliderMaxLabel3 = new javax.swing.JLabel();
        eMSliderMinLabel3 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        moodSlider = new javax.swing.JSlider();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Food");

        foodInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodInputActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Portion");

        foodLrgBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        foodLrgBtn.setText("Large");

        foodMedBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        foodMedBtn.setText("Medium");

        foodSmlBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        foodSmlBtn.setText("Small");

        toDrinkBtn.setText("Next");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Serving");

        javax.swing.GroupLayout foodPanelLayout = new javax.swing.GroupLayout(foodPanel);
        foodPanel.setLayout(foodPanelLayout);
        foodPanelLayout.setHorizontalGroup(
            foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodPanelLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, foodPanelLayout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(foodScroll))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, foodPanelLayout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(foodMedBtn)
                                .addComponent(foodLrgBtn)
                                .addComponent(foodSmlBtn)
                                .addComponent(foodInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(19, 19, 19))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foodPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(toDrinkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        foodPanelLayout.setVerticalGroup(
            foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodLrgBtn))
                .addGap(18, 18, 18)
                .addComponent(foodMedBtn)
                .addGap(18, 18, 18)
                .addComponent(foodSmlBtn)
                .addGap(75, 75, 75)
                .addGroup(foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(toDrinkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        panel.addTab("Food", foodPanel);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Drink");

        drinkInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkInputActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Portion");

        drinkLrgBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        drinkLrgBtn.setText("Large");

        drinkMedBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        drinkMedBtn.setText("Medium");

        drinkSmlBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        drinkSmlBtn.setText("Small");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Quantity");

        toMoodBtn.setText("Next");

        javax.swing.GroupLayout drinkPanelLayout = new javax.swing.GroupLayout(drinkPanel);
        drinkPanel.setLayout(drinkPanelLayout);
        drinkPanelLayout.setHorizontalGroup(
            drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drinkPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toMoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(drinkPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(drinkPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drinkScroll))
                    .addGroup(drinkPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(drinkPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(drinkLrgBtn))
                            .addGroup(drinkPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drinkSmlBtn)
                                    .addComponent(drinkMedBtn)))))
                    .addGroup(drinkPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(drinkInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 165, Short.MAX_VALUE))
        );
        drinkPanelLayout.setVerticalGroup(
            drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinkPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinkInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinkLrgBtn))
                .addGap(18, 18, 18)
                .addComponent(drinkMedBtn)
                .addGap(18, 18, 18)
                .addComponent(drinkSmlBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(drinkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinkScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(toMoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        panel.addTab("Drink", drinkPanel);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Mood");

        moodInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodInputjTextField3ActionPerformed(evt);
            }
        });

        eMSliderMaxLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eMSliderMaxLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eMSliderMaxLabel3.setText("10");

        eMSliderMinLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eMSliderMinLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eMSliderMinLabel3.setText("0");

        submitBtn.setText("Submit");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Satisfaction");

        moodSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moodSliderMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout moodPanelLayout = new javax.swing.GroupLayout(moodPanel);
        moodPanel.setLayout(moodPanelLayout);
        moodPanelLayout.setHorizontalGroup(
            moodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moodPanelLayout.createSequentialGroup()
                .addGroup(moodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moodPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator11))
                    .addGroup(moodPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(eMSliderMinLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moodSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eMSliderMaxLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(moodPanelLayout.createSequentialGroup()
                .addGroup(moodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moodPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(moodPanelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(moodInput, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(moodPanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        moodPanelLayout.setVerticalGroup(
            moodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moodPanelLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(moodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moodInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moodPanelLayout.createSequentialGroup()
                        .addComponent(moodSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moodPanelLayout.createSequentialGroup()
                        .addComponent(eMSliderMaxLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moodPanelLayout.createSequentialGroup()
                        .addComponent(eMSliderMinLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)))
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        panel.addTab("Mood", moodPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void drinkInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinkInputActionPerformed

    private void foodInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodInputActionPerformed

    private void moodInputjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodInputjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moodInputjTextField3ActionPerformed

    private void moodSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moodSliderMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_moodSliderMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField drinkInput;
    private javax.swing.JRadioButton drinkLrgBtn;
    private javax.swing.JRadioButton drinkMedBtn;
    private javax.swing.JPanel drinkPanel;
    private javax.swing.JSpinner drinkScroll;
    private javax.swing.JRadioButton drinkSmlBtn;
    private javax.swing.JSlider eMSlider;
    private javax.swing.JSlider eMSlider1;
    private javax.swing.JLabel eMSliderMaxLabel;
    private javax.swing.JLabel eMSliderMaxLabel1;
    private javax.swing.JLabel eMSliderMaxLabel3;
    private javax.swing.JLabel eMSliderMinLabel;
    private javax.swing.JLabel eMSliderMinLabel1;
    private javax.swing.JLabel eMSliderMinLabel3;
    private javax.swing.JTextField foodInput;
    private javax.swing.JRadioButton foodLrgBtn;
    private javax.swing.JRadioButton foodMedBtn;
    private javax.swing.JPanel foodPanel;
    private javax.swing.JSpinner foodScroll;
    private javax.swing.JRadioButton foodSmlBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField moodInput;
    private javax.swing.JPanel moodPanel;
    private javax.swing.JSlider moodSlider;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton toDrinkBtn;
    private javax.swing.JButton toMoodBtn;
    // End of variables declaration//GEN-END:variables

    public JTextField getMoodInput() {
        return moodInput;
    }

    public void setMoodInput(JTextField moodInput) {
        this.moodInput = moodInput;
    }

    public JPanel getMoodPanel() {
        return moodPanel;
    }

    public void setMoodPanel(JPanel moodPanel) {
        this.moodPanel = moodPanel;
    }

    public JSlider getMoodSlider() {
        return moodSlider;
    }

    public void setMoodSlider(JSlider moodSlider) {
        this.moodSlider = moodSlider;
    }

    public JTabbedPane getPanel() {
        return panel;
    }

    public void setPanel(JTabbedPane panel) {
        this.panel = panel;
    }

    public JButton getSubmitBtn() {
        return submitBtn;
    }

    public void setSubmitBtn(JButton submitBtn) {
        this.submitBtn = submitBtn;
    }

    public JButton getToDrinkBtn() {
        return toDrinkBtn;
    }

    public void setToDrinkBtn(JButton toDrinkBtn) {
        this.toDrinkBtn = toDrinkBtn;
    }

    public JButton getToMoodBtn() {
        return toMoodBtn;
    }

    public void setToMoodBtn(JButton toMoodBtn) {
        this.toMoodBtn = toMoodBtn;
    }

    public JTextField getDrinkInput() {
        return drinkInput;
    }

    public void setDrinkInput(JTextField drinkInput) {
        this.drinkInput = drinkInput;
    }

    public JRadioButton getDrinkLrgBtn() {
        return drinkLrgBtn;
    }

    public void setDrinkLrgBtn(JRadioButton drinkLrgBtn) {
        this.drinkLrgBtn = drinkLrgBtn;
    }

    public JRadioButton getDrinkMedBtn() {
        return drinkMedBtn;
    }

    public void setDrinkMedBtn(JRadioButton drinkMedBtn) {
        this.drinkMedBtn = drinkMedBtn;
    }

    public JPanel getDrinkPanel() {
        return drinkPanel;
    }

    public void setDrinkPanel(JPanel drinkPanel) {
        this.drinkPanel = drinkPanel;
    }

    public JSpinner getDrinkScroll() {
        return drinkScroll;
    }

    public void setDrinkScroll(JSpinner drinkScroll) {
        this.drinkScroll = drinkScroll;
    }

    public JRadioButton getDrinkSmlBtn() {
        return drinkSmlBtn;
    }

    public void setDrinkSmlBtn(JRadioButton drinkSmlBtn) {
        this.drinkSmlBtn = drinkSmlBtn;
    }

    public JTextField getFoodInput() {
        return foodInput;
    }

    public void setFoodInput(JTextField foodInput) {
        this.foodInput = foodInput;
    }

    public JRadioButton getFoodLrgBtn() {
        return foodLrgBtn;
    }

    public void setFoodLrgBtn(JRadioButton foodLrgBtn) {
        this.foodLrgBtn = foodLrgBtn;
    }

    public JRadioButton getFoodMedBtn() {
        return foodMedBtn;
    }

    public void setFoodMedBtn(JRadioButton foodMedBtn) {
        this.foodMedBtn = foodMedBtn;
    }

    public JPanel getFoodPanel() {
        return foodPanel;
    }

    public void setFoodPanel(JPanel foodPanel) {
        this.foodPanel = foodPanel;
    }

    public JSpinner getFoodScroll() {
        return foodScroll;
    }

    public void setFoodScroll(JSpinner foodScroll) {
        this.foodScroll = foodScroll;
    }

    public JRadioButton getFoodSmlBtn() {
        return foodSmlBtn;
    }

    public void setFoodSmlBtn(JRadioButton foodSmlBtn) {
        this.foodSmlBtn = foodSmlBtn;
    }

    

}
