/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

/**
 *
 * @author john
 */
public class NotificationViewPanel extends javax.swing.JPanel {

    private int accountID;

    /**
     * Creates new form NotificationViewPanel
     */
    public NotificationViewPanel(int accountID) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helloLabel = new javax.swing.JLabel();
        foodLabel = new javax.swing.JLabel();
        drinkLabel = new javax.swing.JLabel();
        moodLabel = new javax.swing.JLabel();

        helloLabel.setText("Hello");

        foodLabel.setText("Food");

        drinkLabel.setText("Drink");

        moodLabel.setText("Mood");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moodLabel)
                    .addComponent(foodLabel)
                    .addComponent(helloLabel)
                    .addComponent(drinkLabel))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(helloLabel)
                .addGap(18, 18, 18)
                .addComponent(foodLabel)
                .addGap(18, 18, 18)
                .addComponent(drinkLabel)
                .addGap(18, 18, 18)
                .addComponent(moodLabel)
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the accountID
     */
    public int getAccountID() {
        return accountID;
    }

    /**
     * @param accountID the accountID to set
     */
    public void setAccountID(int accountID) {
        this.accountID = accountID;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel drinkLabel;
    private javax.swing.JLabel foodLabel;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JLabel moodLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the drinkLabel
     */
    public javax.swing.JLabel getDrinkLabel() {
        return drinkLabel;
    }

    /**
     * @param drinkLabel the drinkLabel to set
     */
    public void setDrinkLabel(javax.swing.JLabel drinkLabel) {
        this.drinkLabel = drinkLabel;
    }

    /**
     * @return the foodLabel
     */
    public javax.swing.JLabel getFoodLabel() {
        return foodLabel;
    }

    /**
     * @param foodLabel the foodLabel to set
     */
    public void setFoodLabel(javax.swing.JLabel foodLabel) {
        this.foodLabel = foodLabel;
    }

    /**
     * @return the helloLabel
     */
    public javax.swing.JLabel getHelloLabel() {
        return helloLabel;
    }

    /**
     * @param helloLabel the helloLabel to set
     */
    public void setHelloLabel(javax.swing.JLabel helloLabel) {
        this.helloLabel = helloLabel;
    }

    /**
     * @return the moodLabel
     */
    public javax.swing.JLabel getMoodLabel() {
        return moodLabel;
    }

    /**
     * @param moodLabel the moodLabel to set
     */
    public void setMoodLabel(javax.swing.JLabel moodLabel) {
        this.moodLabel = moodLabel;
    }
}
